/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/design-system/neutralTheme.ts
 * Command: astryx theme build src/design-system/neutralTheme.ts
 * Generated: 2026-07-13T23:21:25.886Z
 */

// Generated by astryx theme build
export {};

declare module "@astryxdesign/core/Heading" {
  interface XDSHeadingLevelMap {
    "1": true;
    "2": true;
    "3": true;
    "4": true;
    "5": true;
    "6": true;
  }
}

declare module "@astryxdesign/core/Badge" {
  interface XDSBadgeVariantMap {
    gray: true;
  }
}
