/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/design-system/neutralTheme.ts
 * Command: astryx theme build src/design-system/neutralTheme.ts
 * Generated: 2026-07-13T23:21:25.884Z
 */

import type { DefinedTheme } from "@astryxdesign/core/theme";
import type { IconRegistry } from "@astryxdesign/core/Icon";
export declare const neutralIconRegistry: IconRegistry;
export declare const neutralTheme: DefinedTheme;
