// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
  greet: (name: string) => __TAURI_INVOKE<string>("greet", { name }),
  startWatching: (path: string) =>
    typedError<null, string>(__TAURI_INVOKE("start_watching", { path })),
  stopWatching: () => typedError<null, string>(__TAURI_INVOKE("stop_watching")),
  createCharacter: (input: CreateCharacterInput) =>
    typedError<Character, string>(__TAURI_INVOKE("create_character", { input })),
};

/* Types */
export type Character = {
  id: string;
  bookId: string;
  name: string;
  role: string;
  attributes: { [key in string]: string };
  createdAt: string;
  bio: string;
};

export type CreateCharacterInput = {
  /**
   *  Filesystem path to the book's folder — the character file is written
   *  to `<book_dir>/characters/<slug>.md`.
   */
  bookDir: string;
  bookId: string;
  name: string;
  role: string;
  bio?: string;
  attributes?: { [key in string]: string };
};

/* Tauri Specta runtime */
async function typedError<T, E>(
  result: Promise<T>,
): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
  try {
    return { status: "ok", data: await result };
  } catch (e) {
    if (e instanceof Error) throw e;
    return { status: "error", error: e as any };
  }
}
